name: Trigger auto deployment for container-app-ctwpkxv47k63q

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-ctwpkxv47k63q-AutoDeployTrigger-af04ad99-195c-49b7-aa06-2088102d16b5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPCTWPKXV47K63Q_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPCTWPKXV47K63Q_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPCTWPKXV47K63Q_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPCTWPKXV47K63Q_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPCTWPKXV47K63Q_REGISTRY_PASSWORD }}
          containerAppName: container-app-ctwpkxv47k63q
          resourceGroup: flaskbasicbd6c8591
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


